<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $full_name
 * @property string $username
 * @property string $email
 * @property string $phone
 * @property string $password
 * @property int $role
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $password2;

    public static function tableName()
    {
        return 'user';
    }

    /**
     * Finds an identity by the given ID.
     *
     * @param string|int $id the ID to be looked for
     * @return IdentityInterface|null the identity object that matches the given ID.
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * Finds an identity by the given token.
     *
     * @param string $token the token to be looked for
     * @return IdentityInterface|null the identity object that matches the given token.
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * @return int|string current user ID
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string|null current user auth key
     */
    public function getAuthKey()
    {
        return null;
    }

    /**
     * @param string $authKey
     * @return bool|null if auth key is valid for current user
     */
    public function validateAuthKey($authKey)
    {
        return false;
    }

    public static function findByUsername($username)
    {
        return User::findOne(['username' => $username]);;
    }

    public function validatePassword($password)
    {
        return $this->password === md5($password);
    }

    public function beforeSave($insert)
    {
        $this->password = md5($this -> password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function isAdmin(){
        return $this ->role == 1;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['full_name', 'username', 'email', 'phone', 'password'], 'required'],
            [['role'], 'integer'],
            ['username', 'unique'],
            ['password2', 'compare', 'compareAttribute' => 'password'],
            [['email'],'email'],
            ['username', 'match', 'pattern' => '/^[A-Za-z]\w*$/u', 'message'=>'Латиница'],
            ['full_name', 'match', 'pattern' => '/^[А-Яа-яЁё -]*$/u', 'message'=>'Кирил'],
            [['full_name', 'username', 'email', 'phone'], 'string', 'max' => 50],
            [['password'], 'string', 'max' => 40],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'full_name' => 'ФИО',
            'username' => 'Логин',
            'email' => 'Почта',
            'phone' => 'Номер телефона',
            'password' => 'Пароль',
            'password2' => 'Повторите пароль',
            'role' => 'Role',
        ];
    }
}
